arb-dir: lib/common/translation
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: lib/common/translation/untranslated_messages.json