name: propresenter_remote
description: A new Flutter project.

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.10.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Web
  flutter_web_plugins:
    sdk: flutter

  # http via dio
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1

  # riverpod
  flutter_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2
  freezed_annotation: ^2.4.1

  # propresenter
  propresenter_api: ^0.3.0

  
  # logging
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1

  # router
  go_router: ^10.1.0
  
  hive_flutter: ^1.1.0

  keep_screen_on: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.6
  json_serializable: ^6.7.1
  custom_lint: ^0.5.2
  freezed: ^2.4.1
  riverpod_lint: ^2.0.1

flutter:
  generate: true
  uses-material-design: true